;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="UI.Popup.Quest",NewTagName="UI.Popup.QuestJournal")
+GameplayTagList=(Tag="Ability.Carry.Aim",DevComment="")
+GameplayTagList=(Tag="Ability.Reaction.Potion",DevComment="포션 효과를 처리하는 대상 Reaction Ability 공통 분류")
+GameplayTagList=(Tag="Event.Carry.Aim.End",DevComment="")
+GameplayTagList=(Tag="Event.Carry.Aim.Start",DevComment="")
+GameplayTagList=(Tag="Event.Carry.Pickup",DevComment="")
+GameplayTagList=(Tag="Event.Carry.Throw",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Potion.Burst",DevComment="포션 파손 순간 표현")
+GameplayTagList=(Tag="GameplayCue.Potion.FartLaunch",DevComment="불방귀 포션 효과 표현")
+GameplayTagList=(Tag="GameplayCue.Potion.Giant",DevComment="거대화 포션 효과 표현")
+GameplayTagList=(Tag="GameplayCue.Potion.Player.FartLaunch",DevComment="")
+GameplayTagList=(Tag="Immunity.Potion.All",DevComment="모든 포션 효과 면역 상태")
+GameplayTagList=(Tag="Immunity.Potion.FartLaunch",DevComment="불방귀 포션 효과 면역 상태")
+GameplayTagList=(Tag="Immunity.Potion.Giant",DevComment="거대화 포션 효과 면역 상태")
+GameplayTagList=(Tag="Immunity.Potion.Bouncy",DevComment="탱글 포션 효과 면역 상태")
+GameplayTagList=(Tag="Potion.Effect.Bouncy",DevComment="")
+GameplayTagList=(Tag="Potion.Effect.Explosion",DevComment="2차 조합")
+GameplayTagList=(Tag="Potion.Effect.FartLaunch",DevComment="1차 조합")
+GameplayTagList=(Tag="Potion.Effect.Giant",DevComment="")
+GameplayTagList=(Tag="Potion.Effect.Gust",DevComment="")
+GameplayTagList=(Tag="Potion.Effect.Heat",DevComment="")
+GameplayTagList=(Tag="Potion.Effect.Reset",DevComment="")
+GameplayTagList=(Tag="Potion.Effect.Slime",DevComment="1차 조합")
+GameplayTagList=(Tag="Potion.Effect.Stench",DevComment="")
+GameplayTagList=(Tag="State.Carry.Aiming",DevComment="")
+GameplayTagList=(Tag="State.Effect.Giant",DevComment="대상에게 거대화 효과가 적용 중인 상태")
+GameplayTagList=(Tag="State.Effect.Bouncy",DevComment="대상에게 탱글 효과가 적용 중인 상태")
+GameplayTagList=(Tag="State.Reaction.Potion",DevComment="대상이 포션 Reaction Ability를 수행 중인 상태")
+GameplayTagList=(Tag="UI.Popup.QuestJournal",DevComment="")

